name: build bitnami/bitnami-docker-nginx docker image on arm64

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: docker-build
    steps:

      - name: Get latest tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF_NAME}

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.tag }}
          repository: bitnami/bitnami-docker-nginx
          path: bitnami-docker-nginx

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: bitnami-docker-nginx
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bitnami-docker-nginx-arm64:${{ steps.vars.outputs.tag }}
